#page title
page_title                                : DNN Performance Profiler                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/download.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : DNN Performance Profiler                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Performance estimation of Image recognition DNNs on your mobile-phone 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Vinod Ganesan, Surya Selvam                                
your_link                                 :                
your_city                                 :                               
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

    #  - title                                 : GitHub Pages Jekyll Theme
    #    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voil√°!
    #    fontawesome_icon_name                 : magic
    
     - title                                 : Step-1
       description                           : Download the App from the link provided above. 
       fontawesome_icon_name                 : book

     - title                                 : Step-2
       description                           : Install it and open it.
       fontawesome_icon_name                 : book
    
     - title                                 : Step-3
       description                           : Click allow when the app asks permission to access storage.
       fontawesome_icon_name                 : book
    
     - title                                 : Step-4
       description                           : Bring the app to the foreground, and let it run. It takes around 10-20 minutes to complete, depending on the device.
       fontawesome_icon_name                 : book
     
     - title                                 : Step-5
       description                           : Please don't lock the phone or use it while the app is running.
       fontawesome_icon_name                 : book
    
     - title                                 : Step-6
       description                           : Please have the mobile connected to the internet through-out the process.
       fontawesome_icon_name                 : book
    
     - title                                 : Step-7
       description                           : When the app completes execution, it will send the latency report automatically to a backend server, and will notify you of completion
       fontawesome_icon_name                 : book
    
     - title                                 : Step-8
       description                           : In-case there is a failure, you will be notified. Please contact us
       fontawesome_icon_name                 : book


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
#theme: jekyll-theme-minimal
